[2022-09-19 23:42:32,427] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: dag2.multiply scheduled__2022-09-19T11:09:00+00:00 [queued]>
[2022-09-19 23:42:32,434] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: dag2.multiply scheduled__2022-09-19T11:09:00+00:00 [queued]>
[2022-09-19 23:42:32,434] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 23:42:32,434] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-09-19 23:42:32,434] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 23:42:32,446] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): multiply> on 2022-09-19 11:09:00+00:00
[2022-09-19 23:42:32,448] {standard_task_runner.py:52} INFO - Started process 1590 to run task
[2022-09-19 23:42:32,450] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dag2', 'multiply', 'scheduled__2022-09-19T11:09:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmprdrn27li', '--error-file', '/tmp/tmp8hgcyy6m']
[2022-09-19 23:42:32,451] {standard_task_runner.py:80} INFO - Job 5: Subtask multiply
[2022-09-19 23:42:32,479] {logging_mixin.py:109} INFO - Running <TaskInstance: dag2.multiply scheduled__2022-09-19T11:09:00+00:00 [running]> on host 8eb0791cd07b
[2022-09-19 23:42:32,507] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag2
AIRFLOW_CTX_TASK_ID=multiply
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T11:09:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T11:09:00+00:00
[2022-09-19 23:42:32,508] {python.py:175} INFO - Done. Returned value was: 50
[2022-09-19 23:42:32,519] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=dag2, task_id=multiply, execution_date=20220919T110900, start_date=20220919T181232, end_date=20220919T181232
[2022-09-19 23:42:32,541] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-19 23:42:32,562] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
