[2022-09-19 23:44:13,798] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: dag2.multiply manual__2022-09-19T18:14:07.975959+00:00 [queued]>
[2022-09-19 23:44:13,805] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: dag2.multiply manual__2022-09-19T18:14:07.975959+00:00 [queued]>
[2022-09-19 23:44:13,805] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 23:44:13,805] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-09-19 23:44:13,805] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 23:44:13,816] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): multiply> on 2022-09-19 18:14:07.975959+00:00
[2022-09-19 23:44:13,821] {standard_task_runner.py:52} INFO - Started process 1715 to run task
[2022-09-19 23:44:13,826] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dag2', 'multiply', 'manual__2022-09-19T18:14:07.975959+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpj6lpxmuz', '--error-file', '/tmp/tmplipcbwi0']
[2022-09-19 23:44:13,827] {standard_task_runner.py:80} INFO - Job 12: Subtask multiply
[2022-09-19 23:44:13,864] {logging_mixin.py:109} INFO - Running <TaskInstance: dag2.multiply manual__2022-09-19T18:14:07.975959+00:00 [running]> on host 8eb0791cd07b
[2022-09-19 23:44:13,900] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag2
AIRFLOW_CTX_TASK_ID=multiply
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T18:14:07.975959+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-19T18:14:07.975959+00:00
[2022-09-19 23:44:13,900] {python.py:175} INFO - Done. Returned value was: 50
[2022-09-19 23:44:13,913] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=dag2, task_id=multiply, execution_date=20220919T181407, start_date=20220919T181413, end_date=20220919T181413
[2022-09-19 23:44:13,957] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-19 23:44:13,990] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
