[2022-09-19 18:24:03,923] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: dag2.multiply scheduled__2022-09-19T11:09:00+00:00 [queued]>
[2022-09-19 18:24:03,929] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: dag2.multiply scheduled__2022-09-19T11:09:00+00:00 [queued]>
[2022-09-19 18:24:03,929] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 18:24:03,929] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-09-19 18:24:03,929] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 18:24:03,940] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): multiply> on 2022-09-19 11:09:00+00:00
[2022-09-19 18:24:03,942] {standard_task_runner.py:52} INFO - Started process 1616 to run task
[2022-09-19 18:24:03,945] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dag2', 'multiply', 'scheduled__2022-09-19T11:09:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpc02b1sx9', '--error-file', '/tmp/tmp5cnyg12h']
[2022-09-19 18:24:03,945] {standard_task_runner.py:80} INFO - Job 16: Subtask multiply
[2022-09-19 18:24:03,974] {logging_mixin.py:109} INFO - Running <TaskInstance: dag2.multiply scheduled__2022-09-19T11:09:00+00:00 [running]> on host 0eef05c196e2
[2022-09-19 18:24:04,005] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag2
AIRFLOW_CTX_TASK_ID=multiply
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T11:09:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T11:09:00+00:00
[2022-09-19 18:24:04,006] {python.py:175} INFO - Done. Returned value was: 50
[2022-09-19 18:24:04,018] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=dag2, task_id=multiply, execution_date=20220919T110900, start_date=20220919T125403, end_date=20220919T125404
[2022-09-19 18:24:04,036] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-19 18:24:04,058] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
