[2022-09-19 23:44:17,778] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: dag2.success manual__2022-09-19T18:14:07.975959+00:00 [queued]>
[2022-09-19 23:44:17,785] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: dag2.success manual__2022-09-19T18:14:07.975959+00:00 [queued]>
[2022-09-19 23:44:17,785] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 23:44:17,785] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-09-19 23:44:17,785] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 23:44:17,795] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): success> on 2022-09-19 18:14:07.975959+00:00
[2022-09-19 23:44:17,798] {standard_task_runner.py:52} INFO - Started process 1724 to run task
[2022-09-19 23:44:17,800] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dag2', 'success', 'manual__2022-09-19T18:14:07.975959+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmp6vkrr_mn', '--error-file', '/tmp/tmp6393f3i9']
[2022-09-19 23:44:17,801] {standard_task_runner.py:80} INFO - Job 14: Subtask success
[2022-09-19 23:44:17,835] {logging_mixin.py:109} INFO - Running <TaskInstance: dag2.success manual__2022-09-19T18:14:07.975959+00:00 [running]> on host 8eb0791cd07b
[2022-09-19 23:44:17,871] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag2
AIRFLOW_CTX_TASK_ID=success
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T18:14:07.975959+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-19T18:14:07.975959+00:00
[2022-09-19 23:44:17,872] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-19 23:44:17,872] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo success']
[2022-09-19 23:44:17,878] {subprocess.py:85} INFO - Output:
[2022-09-19 23:44:17,879] {subprocess.py:89} INFO - success
[2022-09-19 23:44:17,879] {subprocess.py:93} INFO - Command exited with return code 0
[2022-09-19 23:44:17,894] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=dag2, task_id=success, execution_date=20220919T181407, start_date=20220919T181417, end_date=20220919T181417
[2022-09-19 23:44:17,932] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-19 23:44:17,955] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
