[2022-09-19 22:07:54,788] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: dag2.multiply manual__2022-09-19T16:37:48.646650+00:00 [queued]>
[2022-09-19 22:07:54,795] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: dag2.multiply manual__2022-09-19T16:37:48.646650+00:00 [queued]>
[2022-09-19 22:07:54,795] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 22:07:54,795] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-09-19 22:07:54,795] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-09-19 22:07:54,805] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): multiply> on 2022-09-19 16:37:48.646650+00:00
[2022-09-19 22:07:54,807] {standard_task_runner.py:52} INFO - Started process 4739 to run task
[2022-09-19 22:07:54,809] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dag2', 'multiply', 'manual__2022-09-19T16:37:48.646650+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpxm1jqswq', '--error-file', '/tmp/tmpcrgybln8']
[2022-09-19 22:07:54,810] {standard_task_runner.py:80} INFO - Job 26: Subtask multiply
[2022-09-19 22:07:54,841] {logging_mixin.py:109} INFO - Running <TaskInstance: dag2.multiply manual__2022-09-19T16:37:48.646650+00:00 [running]> on host 0eef05c196e2
[2022-09-19 22:07:54,874] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag2
AIRFLOW_CTX_TASK_ID=multiply
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T16:37:48.646650+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-19T16:37:48.646650+00:00
[2022-09-19 22:07:54,875] {python.py:175} INFO - Done. Returned value was: 50
[2022-09-19 22:07:54,886] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=dag2, task_id=multiply, execution_date=20220919T163748, start_date=20220919T163754, end_date=20220919T163754
[2022-09-19 22:07:54,901] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-19 22:07:54,922] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
